---
- name: Render Namespace manifest
  template:
    src: namespace.yml.j2
    dest: "/tmp/aks-namespace-{{ k8s_namespace }}.yaml"

- name: Apply Namespace manifest
  command: kubectl apply -f /tmp/aks-namespace-{{ k8s_namespace }}.yaml
