all:
  children:
    azure_vm:
      hosts:
        vm-cnd-cp2-docs:
          ansible_host: 20.151.118.193
          ansible_user: darioreyesr25
          ansible_ssh_private_key_file: /home/linux/.ssh/id_rsa
          ansible_python_interpreter: "/usr/bin/python3"
          acr_name: acrcndcp2dev
          acr_login_server: acrcndcp2dev.azurecr.io
          acr_username: acrcndcp2dev
          acr_password: 6TyWGCTdBJVKl41yJkZOLcsWeZ1XlsC9jHhxw1LCB9nplZcL0a06JQQJ99CCACBsN54Eqg7NAAACAZCRgu8B

    azure_acr:
      hosts:
        acrcndcp2dev:
          acr_login_server: acrcndcp2dev.azurecr.io

    azure_aks:
      hosts:
        aks-cnd-cp2:
          aks_resource_group: rg-cnd-cp2
          ansible_connection: local
          ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') + '/bin/python' }}"

  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('env', 'VIRTUAL_ENV') + '/bin/python' }}"
