---
- name: Configure VM and Push Image to ACR
  hosts: azure_vm
  become: yes
  roles:
    - acr
  vars_files:
    - ./vars.yml

- name: Configure VM and Deploy Podman Container
  hosts: azure_vm
  become: yes
  roles:
    - vm
  vars_files:
    - ./vars.yml

- name: Deploy application to AKS (run from the VM)
  hosts: azure_vm
  become: yes
  vars_files:
    - ./vars.yml
  roles:
    - aks
