---
- name: Configure VM and Push Image to ACR
  hosts: azure_vm
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - acr
  vars_files:
    - vars.yml
    - secrets.yml